Update b5-assignment

diff --git a/b5-assignment b/b5-assignment
--- a/b5-assignment
+++ b/b5-assignment
@@ -49,3 +49,42 @@ pipeline{
          }
     }
 }
+
+boolean testResult = true
+pipeline {
+  agent any
+   stages {
+    stage ('STAGE_A') {
+      steps {
+        script{
+          try{
+            echo " this is build stage" 
+            sh 'exit 1'  
+          }
+          catch(Exception e){testResult=false}
+       }
+      }
+    }  
+    stage ('STAGE_B') {
+        when {
+         expression {testResult == true }
+        }
+            steps {
+                  echo 'this is stage B Running'
+                  echo 'stage A is successfull'
+                }
+              }
+       stage ('STAGE_C') {
+        when {
+         expression {testResult == false }
+        } 
+            steps {
+                  echo 'this is stage C Running'
+                  echo 'stage A is failed'
+                }
+            }
+         } 
+      }
+      
+
+         
